language: perl
matrix:
    include:
        - perl: '5.30'
          env: ALIEN_INSTALL_TYPE=share
          os: linux
        - perl: '5.28'
          env: ALIEN_INSTALL_TYPE=system
          os: linux
        - perl: '5.22'
          os: linux
        

sudo: required 

branches:
  except:
  - /appveyor/

cache:
  directories:
    - ${HOME}/perl_modules
    - ${HOME}/.alienbuild/plugin_fetch_cache
    - ${HOME}/Library/Caches/Homebrew
    #- /usr/local

before_install:
    # Skip build if the commit message contains [skip travis] or [travis skip]
    #  (from https://github.com/htgoebel/pyinstaller/blob/develop/.travis.yml)
  - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[(skip travis|travis skip)\]'
      && echo "[skip travis] has been found, exiting."
      && exit 0 || true


#  local::lib target is cached
  - cpanm --local-lib=~/perl_modules local::lib && eval $(perl -I ~/perl_modules/lib/perl5/ -Mlocal::lib)
  - cpanm --notest --installdeps .
  

script:
  - export ALIEN_BUILD_PRELOAD=Fetch::Cache
  - perl Makefile.PL
  - make
  - make test
  
