branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry
  - .alienbuild\plugin_fetch_cache

install:
  - if not exist "C:\strawberry" choco install strawberryperl --version 5.26.1.1
  - set ST=C:\strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%

  - cpanm --quiet --notest --installdeps .

  - gcc -v

build_script:
  - set ALIEN_BUILD_PRELOAD=Fetch::Cache
  - perl Makefile.PL

  - gmake
  - gmake test
